name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "d65b9dfb10504765b009830262a5ff0e" },
  { binding = "SHARE", id = "0007c89d72824859b3ccb3885c1820df" }
]